on:
  push:
    branches:
    - main
    paths:
    - src/**
    - docs/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docs/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Generate docfx Documentation
    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - run: dotnet restore
    - run: dotnet tool update -g docfx
    - run: docfx docs/docfx.json

    - name: Publish
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true
